In [57]:
from sklearn.datasets import load_digits
from sklearn.model_selection import cross_val_score, train_test_split
import numpy as np
from sklearn.metrics import accuracy_score
import math
from sklearn.ensemble import RandomForestClassifier
import scipy

In [33]:
Xdig,ydig = load_digits(return_X_y=True)

In [34]:
Xdig[1:5, :]

array([[ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,
         9.,  0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7.,
        15., 16., 16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,
         0.,  0.,  0.,  1., 16., 16.,  6.,  0.,  0.,  0.,  0.,  1., 16.,
        16.,  6.,  0.,  0.,  0.,  0.,  0., 11., 16., 10.,  0.,  0.],
       [ 0.,  0.,  0.,  4., 15., 12.,  0.,  0.,  0.,  0.,  3., 16., 15.,
        14.,  0.,  0.,  0.,  0.,  8., 13.,  8., 16.,  0.,  0.,  0.,  0.,
         1.,  6., 15., 11.,  0.,  0.,  0.,  1.,  8., 13., 15.,  1.,  0.,
         0.,  0.,  9., 16., 16.,  5.,  0.,  0.,  0.,  0.,  3., 13., 16.,
        16., 11.,  5.,  0.,  0.,  0.,  0.,  3., 11., 16.,  9.,  0.],
       [ 0.,  0.,  7., 15., 13.,  1.,  0.,  0.,  0.,  8., 13.,  6., 15.,
         4.,  0.,  0.,  0.,  2.,  1., 13., 13.,  0.,  0.,  0.,  0.,  0.,
         2., 15., 11.,  1.,  0.,  0.,  0.,  0.,  0.,  1., 12., 12.,  1.,
         0.,  0.,  0.,  0.,  0.,  1., 10.,  8.,  0.,  0.,  

In [35]:
X_train, X_test, y_train, y_test = train_test_split(Xdig, ydig, test_size = 0.25, shuffle=False)

## 1 task

In [4]:
list = np.zeros((len(X_test), 2))

In [6]:
sum((X_test[1] - X_train[50])**2)

2814.0

In [7]:
for i in range(len(X_test)):
    ind = 0
    z = 10000
    for j in range(len(X_train)):
        b = sum((X_test[i] - X_train[j])**2)
        if b < z:
            z = b
            ind = y_train[j]
    list[i, 0] = z
    list[i, 1] = ind
        
        
        
        

In [10]:
1 - accuracy_score(y_test, list[:, 1])

0.0377777777777778

In [11]:
with open("1NN_vs_Random_forest_1.txt", "w") as fout:
        fout.write(str(1 - accuracy_score(y_test, list[:, 1])))

## 2 task

In [13]:
forest = RandomForestClassifier(n_estimators=1000)

In [14]:
forest.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1000, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [15]:
prediction = forest.predict(X_test)

In [18]:
1 - accuracy_score(y_test, prediction)

0.06666666666666665

In [19]:
with open("1NN_vs_Random_forest_2.txt", "w") as fout:
        fout.write(str(1 - accuracy_score(y_test, prediction)))

## Альтернативный метод первого задания

In [ ]:
# Добавляем в матрицу признаков вектор с ответами

In [12]:
np.reshape(y_train, (1347, 1)).shape

(1347, 1)

In [53]:
X_train = np.hstack((X_train, np.reshape(y_train, (1347, 1))))

In [ ]:
#Сортируем полученную матрицу по по вектору с метками классов

In [54]:
X_train = X_train[X_train[:,-1].argsort()]

In [55]:
X_train[:, -1]

array([0., 0., 0., ..., 9., 9., 9.])

In [61]:
X_train[([-1] > 1)]

TypeError: '>' not supported between instances of 'list' and 'int'

In [65]:
np.where(X_train[:, -1] == 0)

(array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
         52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
         65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
         78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
         91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
        104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
        117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
        130, 131, 132, 133, 134], dtype=int64),)